apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-storefront-mf-navigator
  labels:
    app.kubernetes.io/version: "0.3"
  annotations:
    tekton.dev/pipelines.minVersion: "0.21.0"
    tekton.dev/displayName: "prep-storefront-mf-navigator"
spec:
  description: >-
    deploy-storefront-mf-navigator
  workspaces:
    - name: source
      description: shared workspace 
  params:
  - name: project-name
    description: project-name 
  steps:
    - name: deploy-storefront-mf-navigator
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli
      script: |
        #!/bin/bash
        oc project $(params.project-name)  > /dev/null 2>&1
        if [ $? != 0 ]; then 
          oc new-project $(params.project-name)
        fi

        cd $(workspaces.source.path)/frontend-single-spa/navigator
        oc apply -f deployment/kubernetes.yaml
        oc expose svc/storefront-mf-navigator
        echo "Done deploying storefront-mf-navigator"

        ROUTE=$(oc get route storefront-mf-navigator --template='{{ .spec.host }}')
        echo "http://${ROUTE}/js/app.js"
