apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-gitops-repo
spec:
  params:
  - name: project-name-prefix
  - name: environment
  - name: argo-app-name
  - name: config-git-url
  - name: app-git-url
  workspaces:
  - name: app-source
  - name: config-source
  steps:
  - name: configure-yaml
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.config-source.path)"
    script: |
      #!/usr/bin/env sh
      set -e
      FILE=$(workspaces.app-source.path)/revision.txt
      if [ -f "$FILE" ]; then
        source $(workspaces.app-source.path)/revision.txt
      else
        REVISION=$(date +%s) 
      fi
      echo REVISION: $REVISION
      
      cd $(workspaces.config-source.path)    
      cd service-catalog-quarkus-reactive
      cd $(params.environment)
      rm -f lastcommit.md
      rm -f kubernetes.yaml
      rm -f openshift.yaml

      sed "s/<project-name>/app-mod-argocd-$(params.environment)/g" $(workspaces.app-source.path)/service-catalog-quarkus-reactive/deployment/kubernetes.yaml.template > kubernetes-temp.yaml
      sed "s/<version>/$REVISION/g" kubernetes-temp.yaml > kubernetes.yaml
      rm -f kubernetes-temp.yaml
      cp $(workspaces.app-source.path)/service-catalog-quarkus-reactive/deployment/openshift.yaml openshift.yaml
  - name: commit-push-changes-gitops
    image: alpine/git:v2.30.2
    workingDir: "$(workspaces.config-source.path)"
    script: |
      #!/usr/bin/env sh
      set -e
      cd service-catalog-quarkus-reactive
      cd $(params.environment)
      eval $(ssh-agent)
      ssh-add ~/.ssh/id_*

      git config --global user.email "tekton@tekton.dev"
      git config --global user.name "Tekton Pipeline"
      git add .
      git commit --allow-empty -m "[Tekton] updating $(params.environment)"
      git push origin main
---