apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: tools
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.tekton: apiKey, login
---